#release configuration
#Mon Oct 07 15:29:48 TRT 2024
projectVersionPolicyId=default
project.dev.io.jenkins.plugins\:appcircle-testing-distribution=1.12-SNAPSHOT
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.io.jenkins.plugins\:appcircle-testing-distribution.url=https\://github.com/${gitHubRepo}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
exec.activateProfiles=consume-incrementals,might-produce-incrementals
pushChanges=true
project.rel.io.jenkins.plugins\:appcircle-testing-distribution=1.11
remoteTagging=true
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.io.jenkins.plugins\:appcircle-testing-distribution.developerConnection=scm\:git\:https\://github.com/${gitHubRepo}
project.scm.io.jenkins.plugins\:appcircle-testing-distribution.tag=1.11
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/jenkinsci/appcircle-testing-distribution-plugin
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.io.jenkins.plugins\:appcircle-testing-distribution.connection=scm\:git\:https\://github.com/${gitHubRepo}
scm.tag=1.11
completionGoals=incrementals\:reincrementalify
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
exec.pomFileName=pom.xml
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
